# （一）、Pandas数据结构
#### 目录：
####     1.Series
####     2.Dataframe：构建、操作、内置函数……
####     3.索引对象index

In [1]:
import pandas as pd

### 1. Series

In [2]:
'''1. 通过list构建Series'''
ser_obj = pd.Series(range(10, 20,2))
print (type(ser_obj))
print(ser_obj)

<class 'pandas.core.series.Series'>
0    10
1    12
2    14
3    16
4    18
dtype: int64


In [3]:
# 获取数据
print (ser_obj.values)

# 获取索引
print (ser_obj.index)
#范围索引数据类型

# 预览数据
print (ser_obj.head(3))
#默认输出五行

[10 12 14 16 18]
RangeIndex(start=0, stop=5, step=1)
0    10
1    12
2    14
dtype: int64


In [4]:
'''2. 通过dict构建Series'''
year_data = {2001: 17.8, 2002: 20.1, 2003: 16.5,2004:324,2423:243}
ser_obj2 = pd.Series(year_data)
print (ser_obj2.head(2))
print (ser_obj2.index)
print(ser_obj2)

2001    17.8
2002    20.1
dtype: float64
Int64Index([2001, 2002, 2003, 2004, 2423], dtype='int64')
2001     17.8
2002     20.1
2003     16.5
2004    324.0
2423    243.0
dtype: float64


In [5]:
# name属性【【【【【出问题了！！！】】】】】
ser_obj2.name = '钱'
ser_obj2.index.name = 'year'
print (ser_obj2.head())

year
2001     17.8
2002     20.1
2003     16.5
2004    324.0
2423    243.0
Name: 钱, dtype: float64


### 2. DataFrame

In [13]:
import numpy as np

'''1. 通过ndarray构建DataFrame === 一般是用二维 = = 得复习numpy了'''
array = np.random.rand(5,4)
print (array)

df_obj = pd.DataFrame(array,columns=['a','b','c','d'])
print (df_obj.head())
print(df_obj.sort_values(by='a', ascending=False))

[[0.05782902 0.0809033  0.33156754 0.19493577]
 [0.62796942 0.57765469 0.73671312 0.3359223 ]
 [0.29920211 0.65154339 0.02394759 0.58972836]
 [0.34812741 0.89513238 0.911551   0.8286806 ]
 [0.77395554 0.39687084 0.11014845 0.03218328]]
          a         b         c         d
0  0.057829  0.080903  0.331568  0.194936
1  0.627969  0.577655  0.736713  0.335922
2  0.299202  0.651543  0.023948  0.589728
3  0.348127  0.895132  0.911551  0.828681
4  0.773956  0.396871  0.110148  0.032183
          a         b         c         d
4  0.773956  0.396871  0.110148  0.032183
1  0.627969  0.577655  0.736713  0.335922
3  0.348127  0.895132  0.911551  0.828681
2  0.299202  0.651543  0.023948  0.589728
0  0.057829  0.080903  0.331568  0.194936


In [7]:
'''2. 通过dict构建DataFrame'''
#一个键值对就相当于一列！！但是具体到字典里面的值所用到的一些函数还是不能很清楚
dict_data = {'A': 1., 
             'B': pd.Timestamp('20161217'),
             'C': pd.Series(1, index=list(range(4)),dtype='float32'),
             'D': np.array([3] * 4,dtype='int32'),
             'E' : pd.Categorical(["Python","Java","C++","C#"]),
             'F' : 'ChinaHadoop' }
df_obj2 = pd.DataFrame(dict_data)
print (df_obj2.head())

     A          B    C  D       E            F
0  1.0 2016-12-17  1.0  3  Python  ChinaHadoop
1  1.0 2016-12-17  1.0  3    Java  ChinaHadoop
2  1.0 2016-12-17  1.0  3     C++  ChinaHadoop
3  1.0 2016-12-17  1.0  3      C#  ChinaHadoop


In [33]:
# 增加列
df_obj2['G'] = df_obj2['D'] + 4
print (df_obj2.head())
xxx = pd.DataFrame(df_obj2,columns=['A','B','C','D','E','F','G','H'],index=[0,1,2,3,4])
print(xxx)

     A          B    C  D       E            F  G
0  1.0 2016-12-17  1.0  3  Python  ChinaHadoop  7
1  1.0 2016-12-17  1.0  3    Java  ChinaHadoop  7
2  1.0 2016-12-17  1.0  3     C++  ChinaHadoop  7
3  1.0 2016-12-17  1.0  3      C#  ChinaHadoop  7
     A          B    C    D       E            F    G   H
0  1.0 2016-12-17  1.0  3.0  Python  ChinaHadoop  7.0 NaN
1  1.0 2016-12-17  1.0  3.0    Java  ChinaHadoop  7.0 NaN
2  1.0 2016-12-17  1.0  3.0     C++  ChinaHadoop  7.0 NaN
3  1.0 2016-12-17  1.0  3.0      C#  ChinaHadoop  7.0 NaN
4  NaN        NaT  NaN  NaN     NaN          NaN  NaN NaN


### 3. 索引对象 Index

In [10]:
print (type(ser_obj.index))
print (type(df_obj2.index))

print (df_obj2.index)

<class 'pandas.core.indexes.range.RangeIndex'>
<class 'pandas.core.indexes.numeric.Int64Index'>
Int64Index([0, 1, 2, 3], dtype='int64')


In [11]:
# 索引对象不可变
df_obj2.index[0] = 2

TypeError: Index does not support mutable operations