# np的常用函数


## 转置transpose

In [1]:
import numpy as np

In [2]:
arr = np.random.rand(2,3)
print (arr)
print (arr.transpose())

[[0.78485041 0.88817969 0.34809014]
 [0.32744286 0.97539301 0.94401872]]
[[0.78485041 0.32744286]
 [0.88817969 0.97539301]
 [0.34809014 0.94401872]]


In [3]:
#高维数组的转换(图像里面会用得到转换维度)
#不懂这里！！！
arr3d = np.random.rand(2,3,4)
print (arr3d)
print ('----------------------')
print (arr3d.transpose((1,0,2))) # 多维数组的转置和定义不会

[[[0.28492549 0.60197236 0.45582367 0.21992479]
  [0.1747163  0.69201365 0.85460359 0.65311699]
  [0.62189644 0.25217555 0.16347156 0.29831219]]

 [[0.42826733 0.81396165 0.187138   0.560564  ]
  [0.10162186 0.66419751 0.03261665 0.06969256]
  [0.55461652 0.55020586 0.50693591 0.31741807]]]
----------------------
[[[0.28492549 0.60197236 0.45582367 0.21992479]
  [0.42826733 0.81396165 0.187138   0.560564  ]]

 [[0.1747163  0.69201365 0.85460359 0.65311699]
  [0.10162186 0.66419751 0.03261665 0.06969256]]

 [[0.62189644 0.25217555 0.16347156 0.29831219]
  [0.55461652 0.55020586 0.50693591 0.31741807]]]


## 通用函数 ：ceil；floor；rint；isnan

In [4]:
arr = np.random.randn(2,3)

print (arr)
print (np.ceil(arr))
#向上最接近的整数
print (np.floor(arr))
#向下最接近的整数
print (np.rint(arr))
#四舍五入
print (np.isnan(arr))
#判断元素是否为NaN
#笔记上还有其他的函数

[[ 0.262106   -1.33680008 -1.08562543]
 [ 0.3990978   0.1410074   0.64278274]]
[[ 1. -1. -1.]
 [ 1.  1.  1.]]
[[ 0. -2. -2.]
 [ 0.  0.  0.]]
[[ 0. -1. -1.]
 [ 0.  0.  1.]]
[[False False False]
 [False False False]]


## where

In [5]:
arr = np.random.randn(3,4)
print (arr)

np.where(arr > 0, 1, -1)
#（条件，满足输出，不满足输出）

[[ 2.04688394  0.48063737  1.20876913 -0.93412937]
 [-0.43427472 -1.47755481  0.36882256 -0.08943138]
 [-0.2847686   0.96915893  0.32641235  0.28346922]]


array([[ 1,  1,  1, -1],
       [-1, -1,  1, -1],
       [-1,  1,  1,  1]])

## sum

In [6]:
arr = np.arange(10).reshape(5,2)
print (arr)

print (np.sum(arr))
print (np.sum(arr, axis=0))
print (np.sum(arr, axis=1))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
45
[20 25]
[ 1  5  9 13 17]


## all 和any

In [7]:
import numpy as np
arr = np.random.randn(2,3)
print (arr)

print (np.any(arr > 0))
#有一个就对
print (np.all(arr > 0))
#全部对才对
'''
·用处就是判断一组数据当中，是否===有点类似布尔类型的
·这个也可以应用在pandas中的DataFrame中
'''

[[-1.020184   -0.48466272 -0.8496271 ]
 [ 0.88815825 -0.81911857  0.64570539]]
True
False


'\n·用处就是判断一组数据当中，是否===有点类似布尔类型的\n·这个也可以应用在pandas中的DataFrame中\n'

## unique

In [8]:
arr = np.array([[1, 2, 1], [2, 3, 4]])
print (arr)
print (np.unique(arr))

[[1 2 1]
 [2 3 4]]
[1 2 3 4]
