# 数学建模能用到的知识
    只涉及数学方程转换成函数语言进行求解的过程，参考书籍：《数学建模算法与应用》

In [1]:
import matplotlib.pyplot as plt
import numpy as np
import matplotlib
#jupyter notebook需要加上该命令
%matplotlib inline
# 设置matplotlib正常显示中文和负号!!!
matplotlib.rcParams['font.sans-serif']=['SimHei']   # 用黑体显示中文=====不要改matplotlib里面的配置
matplotlib.rcParams['axes.unicode_minus']=False     # 正常显示负号

In [2]:
#向上转型
print(np.array([1,2,3.0])    )
#多维度
print(np.array([[1, 2], [3, 4]]))
#预设维度=== ?
print(np.array([1, 2, 3], ndmin=2))
#复数=== ?
print(np.array([1, 2, 3], dtype=complex))
#多种数据类型=== ?
x = np.array([(1,2),(3,4)],dtype=[('a','<i4'),('b','<i4')])
print(x)

[1. 2. 3.]
[[1 2]
 [3 4]]
[[1 2 3]]
[1.+0.j 2.+0.j 3.+0.j]
[(1, 2) (3, 4)]


### 1. 线性规划

In [6]:
'''
max： z = 4x1 + 3x2
st:      2x1 + 3x2<=10
           x1 + x2 <=8
           x2 <= 7
           x1,x2 > 0
'''

from scipy.optimize import linprog

c = [4,3]        #默认linprog求解的是最小值，若求最大值，此处c取反即可得到最大值的相反数。
A = [[2,3],[1,1]]
b = [10,8]
x1_bounds = [0,None]
x2_bounds =[0,7]
res = linprog(c,A,b,bounds=(x1_bounds,x2_bounds))
print(res)

     con: array([], dtype=float64)
     fun: 0.0
 message: 'Optimization terminated successfully.'
     nit: 4
   slack: array([10.,  8.])
  status: 0
 success: True
       x: array([0., 0.])


### 2. 多项式拟合

In [4]:
import numpy as np
import matplotlib.pyplot as plt

'''
'''
x = np.arange(1990,1997,1)
y = np.array([70 ,122 ,144 ,152, 174, 196, 202])

z1 = ployfit(x,y,1)  #之前画过原始数据，数据走向为ax+b类型。故采用一次多项式拟合
p1 = np.ploy1d(z1)
yvalue = p1(x)

plt.plot(x,y,'*',label = '原始数据')
plt.plot(z1,yvalue,label = '拟合曲线')

plt.xlabel('x axis')
plt.ylabel('y axis')

plt.legend(loc = 4 )

plt.tittle('多项式拟合')
plt.show()

NameError: name 'ployfit' is not defined